### ISSUE TITLE
Duplicate ID in w3c Validator

### ISSUE THREAD

**Issue by vzaugg** [mebishalnapit/bootstrap-navwalker#1]
Hello, 
After integration in Undescrore Starter Theme and validate by w3c validator... 
It says ID are duplicated in menus and submenus.

To resolve i tried to replace:
LINE 29: 
id="navbar-dropdown-menu-link- 
BY 
id="navbar-dropdown-submenu-link-

to make the difference with:
LINE 194

Does it seems to be a good solution?

**Comment by mebishalnapit** [comment]
@vzaugg 

Yes, that modification done seems to be fine.

Thanks.
Bishal Napit

**Comment by mebishalnapit** [comment]
@vzaugg

Additionally, I have fixed up this issue within this library file too. So, can you once check the same if the issue is still there or not?

Thanks.
Bishal Napit
