### ISSUE TITLE
Container is missing

### ISSUE THREAD

**Issue by codestylist** [mebishalnapit/bootstrap-navwalker#3]
Hello @mebishalnapit .
Thank you very much for sharing this excelent BS Nav Walker which is working with BS 4.3.1 perfect - except the container. I call it this way:

```wp_nav_menu(
array(
'theme_location'  => 'header-menu',
'container_class' => 'collapse navbar-collapse',
'container_id'    => 'navbarCollapse',
'menu_class'      => 'navbar-nav mr-auto nav-pills',
'menu_id'         => '',
'walker'         => new Bootstrap_NavWalker(),
'fallback_cb'    => 'Bootstrap_NavWalker::fallback'
)
```

As I noticed the output of the container is missing. Because I use different container it would be wonderfull if you can have a look into this issue and add the output of the container as well.
Thank you in advance.

**Comment by mebishalnapit** [comment]
@codestylist 

I've checked onto it in my development environment and it seems to be working fine, ie, the code which you have mentioned above.

However, if you are still having the issue then, can you let me know with the link to your site along with the code, which you have managed for your WordPress theme too, to better look onto this issue?

Thanks.
Bishal Napit
