### ISSUE TITLE
Hover and dropdown not working

### ISSUE THREAD

**Issue by DarcieLHenderson** [mebishalnapit/bootstrap-navwalker#4]
Just recently, our nav menu is not hovering the dropdowns anymore and also in addition the mobile version is not showing the whole meu.

**Comment by mebishalnapit** [comment]
@DarcieLHenderson 

This is the library file for WordPress Bootstrap 4 Navigation/NavWalker class only, and such issue will not get created via this library file. I think, you could have JS error on your site and hence the issue might have occurred. So, can you once check it thoroughly and fix those issues and see if that helps?

Thanks.
Bishal Napit

**Comment by DarcieLHenderson** [comment]
Thank you very much Bishal. I will look in that direction.

-Darcie
